---
- hosts: all
  collections:
    - arubanetworks.aoscx
  gather_facts: False

  tasks:
    - name: Create VLAN 300 with description and name
      aoscx_vlan:
        vlan_id: 300
        name: UPLINK_VLAN
        description: This is VLAN 300

    - name: Create VLAN 400 with description and name
      aoscx_vlan:
        vlan_id: 400
        name: DATA_VLAN
        description: This is VLAN 400

    - name: Create VLAN 500 with description and name
      aoscx_vlan:
        vlan_id: 500
        name: VOICE_VLAN
        description: This is VLAN 500

    - name: Create VLAN 600 with description and name
      aoscx_vlan:
        vlan_id: 600
        name: GUEST_VLAN
        description: This is VLAN 600

